# Generated by Django 4.2.2 on 2023-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('company1', 'Company 1'), ('company2', 'Company 2'), ('company3', 'Company 3')], max_length=100)),
                ('pizza_type', models.CharField(max_length=100)),
                ('dough', models.CharField(choices=[('thick', 'Thick'), ('thin', 'Thin')], max_length=100)),
                ('image', models.ImageField(upload_to='pizza_images')),
                ('description', models.TextField()),
            ],
        ),
    ]
