# Generated by Django 4.2.2 on 2023-06-17 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='dough',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.company'),
        ),
    ]
