# Generated by Django 4.2.2 on 2023-06-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_company_alter_pizza_dough_alter_pizza_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='dough',
            field=models.CharField(choices=[('thick', 'Thick'), ('thin', 'Thin')], max_length=100),
        ),
    ]
